name: bloc_chat_app_demo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  rxdart: ^0.27.7
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter:

 
  uses-material-design: true

assets:
    - assets/
